Lost function: L(y, f(x)) = -[y * log(f(x)) + (1 - y) * log(1 - f(x))]

In [14]:
import numpy as np 
a = np.array([1,2,3,4,5])
print(a)
print(np.exp(a))

# help(np.exp)

[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [9]:
import time

a = np.random.rand(10000000)
b = np.random.rand(10000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print( "time used: " + str(1000*(toc-tic)) + " ms")


c = 0
tic = time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print( "time used: " + str(1000*(toc-tic)) + " ms")


2500146.694724446
time used: 4.986047744750977 ms
2500146.694724384
time used: 2639.0182971954346 ms


In [17]:
A = np.array([[56.0, 0 ,4.4, 68],
             [1.2,104,52,8],
             [1.8,135,99,0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [24]:
cal = A.sum(axis=0)
print(cal)
print(cal.reshape(1,4))

[ 59.  239.  155.4  76.9]
[[ 59.  239.  155.4  76.9]]


In [26]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
